apiVersion: apps.example.com/v1alpha1
kind: TestRun
metadata:
  name: smoke-test
  namespace: default
spec:
  appName: mock-app
  timeout: "60s"
  script: |
    local http = require("http")

    print("=== TOPAS Smoke Test ===")

    print("[1/3] Checking /health endpoint...")
    http.expect({
        url    = "http://mock-app-echo:8080/health",
        method = "GET",
        expect = {
            status = 200,
            body   = { status = "ok" }
        }
    })
    print("  ✓ Health check passed")

    print("[2/3] Checking /api/echo endpoint...")
    http.expect({
        url    = "http://mock-app-echo:8080/api/echo?msg=topas",
        method = "GET",
        expect = {
            status = 200,
            body   = { echo = "topas" }
        }
    })
    print("  ✓ Echo endpoint passed")

    print("[3/3] Checking /api/version endpoint...")
    http.expect({
        url    = "http://mock-app-echo:8080/api/version",
        method = "GET",
        expect = {
            status = 200,
            body   = { version = "v1" }
        }
    })
    print("  ✓ Version endpoint passed")

    print("=== ALL TESTS PASSED ===")
